on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: dtolnay/rust-toolchain@nightly
      - run: |
          pip install -U pip
          pip install -r requirements.txt
      - run: |
          maturin build
          pip install target/wheels/dantzig-*.whl
          python -c "import dantzig as dz"
      - run: black python-source/dantzig tests --check
      - run: isort python-source/dantzig tests --check
      - run: ruff python-source/dantzig tests
      - run: mypy
      - run: pytest
  rust-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
         components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: cargo test