on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]
  workflow_dispatch:

jobs:
  publish-wheel:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: dtolnay/rust-toolchain@nightly
      - run: rustup target add ${{ matrix.target }}
      - run: |
          pip install -U pip
          pip install -c requirements.txt maturin
      - run: >
          maturin publish --target ${{ matrix.target }} --skip-existing
          -u matteosantama -p ${{ secrets.pypi_password }} 
